/* The following code was generated by JFlex 1.4.3 on 2/12/13 07:36 PM */

package analizador_lexico;
import static analizador_lexico.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 2/12/13 07:36 PM from the specification file
 * <tt>/Users/yamirsuarez/Downloads/Analizador_Lexico/src/analizador_lexico/Lexer.flex</tt>
 */
class lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\13\1\15\2\0\1\13\22\0\1\13\1\36\5\0\1\12"+
    "\1\6\1\7\1\53\1\54\1\11\1\52\1\0\1\14\12\2\1\10"+
    "\1\5\1\35\1\34\1\33\2\0\1\47\3\1\1\45\1\46\5\1"+
    "\1\50\5\1\1\43\1\51\1\42\1\44\5\1\4\0\1\1\1\0"+
    "\1\20\1\27\1\16\1\40\1\30\1\25\1\1\1\31\1\22\2\1"+
    "\1\17\1\1\1\23\1\26\2\1\1\32\1\21\1\24\1\41\1\1"+
    "\1\37\3\1\1\3\1\0\1\4\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\6\2\1\16"+
    "\1\17\1\20\1\1\4\2\1\21\1\22\1\23\1\14"+
    "\5\2\1\24\4\2\1\25\1\26\1\27\1\30\10\2"+
    "\1\31\1\2\1\32\7\2\1\33\1\34\3\2\1\35"+
    "\2\2\1\36\1\2\1\37\1\2\1\40\1\2\1\41"+
    "\1\2\1\42\1\43\2\2\1\44\1\45";

  private static int [] zzUnpackAction() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\55\0\55\0\55\0\55"+
    "\0\55\0\55\0\55\0\55\0\55\0\264\0\341\0\u010e"+
    "\0\u013b\0\u0168\0\u0195\0\u01c2\0\55\0\u01ef\0\55\0\u021c"+
    "\0\u0249\0\u0276\0\u02a3\0\u02d0\0\207\0\55\0\207\0\u02fd"+
    "\0\u032a\0\u0357\0\u0384\0\u03b1\0\u03de\0\132\0\u040b\0\u0438"+
    "\0\u0465\0\u0492\0\55\0\55\0\55\0\55\0\u04bf\0\u04ec"+
    "\0\u0519\0\u0546\0\u0573\0\u05a0\0\u05cd\0\u05fa\0\132\0\u0627"+
    "\0\132\0\u0654\0\u0681\0\u06ae\0\u06db\0\u0708\0\u0735\0\u0762"+
    "\0\132\0\132\0\u078f\0\u07bc\0\u07e9\0\132\0\u0816\0\u0843"+
    "\0\132\0\u0870\0\132\0\u089d\0\132\0\u08ca\0\132\0\u08f7"+
    "\0\132\0\132\0\u0924\0\u0951\0\132\0\132";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\15\1\17\2\3"+
    "\1\20\1\21\2\3\1\22\1\3\1\23\1\24\2\3"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\3\1\33"+
    "\3\3\1\34\3\3\1\35\1\36\1\37\56\0\2\3"+
    "\13\0\15\3\4\0\13\3\5\0\1\4\66\0\1\40"+
    "\41\0\2\3\13\0\1\3\1\41\1\42\10\3\1\43"+
    "\1\3\4\0\13\3\4\0\2\3\13\0\15\3\4\0"+
    "\1\44\12\3\4\0\2\3\13\0\5\3\1\45\1\3"+
    "\1\46\5\3\4\0\13\3\4\0\2\3\13\0\1\3"+
    "\1\47\6\3\1\50\4\3\4\0\13\3\4\0\2\3"+
    "\13\0\10\3\1\51\4\3\4\0\13\3\4\0\2\3"+
    "\13\0\1\3\1\52\13\3\4\0\13\3\36\0\1\53"+
    "\1\54\1\55\53\0\1\56\21\0\2\3\13\0\13\3"+
    "\1\57\1\3\4\0\13\3\4\0\2\3\13\0\12\3"+
    "\1\60\2\3\4\0\13\3\4\0\2\3\13\0\15\3"+
    "\4\0\4\3\1\61\6\3\4\0\2\3\13\0\15\3"+
    "\4\0\10\3\1\62\2\3\3\0\15\40\1\0\37\40"+
    "\1\0\2\3\13\0\2\3\1\63\12\3\4\0\13\3"+
    "\4\0\2\3\13\0\3\3\1\64\11\3\4\0\13\3"+
    "\4\0\2\3\13\0\2\3\1\65\12\3\4\0\13\3"+
    "\4\0\2\3\13\0\4\3\1\66\10\3\4\0\13\3"+
    "\4\0\2\3\13\0\6\3\1\67\6\3\4\0\13\3"+
    "\4\0\2\3\13\0\10\3\1\70\4\3\4\0\13\3"+
    "\4\0\2\3\13\0\14\3\1\71\4\0\13\3\4\0"+
    "\2\3\13\0\10\3\1\72\4\3\4\0\13\3\4\0"+
    "\2\3\13\0\3\3\1\73\11\3\4\0\13\3\4\0"+
    "\2\3\13\0\4\3\1\74\10\3\4\0\13\3\4\0"+
    "\2\3\13\0\7\3\1\75\5\3\4\0\13\3\4\0"+
    "\2\3\13\0\15\3\4\0\5\3\1\76\5\3\4\0"+
    "\2\3\13\0\15\3\4\0\11\3\1\77\1\3\4\0"+
    "\2\3\13\0\3\3\1\100\11\3\4\0\13\3\4\0"+
    "\2\3\13\0\12\3\1\101\2\3\4\0\13\3\4\0"+
    "\2\3\13\0\14\3\1\102\4\0\13\3\4\0\2\3"+
    "\13\0\6\3\1\103\6\3\4\0\13\3\4\0\2\3"+
    "\13\0\2\3\1\104\12\3\4\0\13\3\4\0\2\3"+
    "\13\0\1\3\1\105\13\3\4\0\13\3\4\0\2\3"+
    "\13\0\12\3\1\106\2\3\4\0\13\3\4\0\2\3"+
    "\13\0\1\3\1\107\13\3\4\0\13\3\4\0\2\3"+
    "\13\0\2\3\1\110\12\3\4\0\13\3\4\0\2\3"+
    "\13\0\15\3\4\0\6\3\1\111\4\3\4\0\2\3"+
    "\13\0\15\3\4\0\12\3\1\112\4\0\2\3\13\0"+
    "\3\3\1\113\11\3\4\0\13\3\4\0\2\3\13\0"+
    "\1\114\14\3\4\0\13\3\4\0\2\3\13\0\6\3"+
    "\1\115\6\3\4\0\13\3\4\0\2\3\13\0\12\3"+
    "\1\116\2\3\4\0\13\3\4\0\2\3\13\0\12\3"+
    "\1\117\2\3\4\0\13\3\4\0\2\3\13\0\15\3"+
    "\4\0\2\3\1\120\10\3\4\0\2\3\13\0\15\3"+
    "\4\0\6\3\1\121\4\3\4\0\2\3\13\0\13\3"+
    "\1\122\1\3\4\0\13\3\4\0\2\3\13\0\2\3"+
    "\1\123\12\3\4\0\13\3\4\0\2\3\13\0\1\3"+
    "\1\124\13\3\4\0\13\3\4\0\2\3\13\0\5\3"+
    "\1\125\7\3\4\0\13\3\4\0\2\3\13\0\6\3"+
    "\1\126\6\3\4\0\13\3\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2430];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\11\11\7\1\1\11\1\1\1\11"+
    "\6\1\1\11\14\1\4\11\50\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return IF;
          }
        case 38: break;
        case 16: 
          { return MENORQUE;
          }
        case 39: break;
        case 2: 
          { lexeme = yytext(); return IDENTIFICADOR;
          }
        case 40: break;
        case 36: 
          { return BOOLEAN;
          }
        case 41: break;
        case 21: 
          { return MAYOROIGUAL;
          }
        case 42: break;
        case 11: 
          { lexeme = yytext(); return COMILLA;
          }
        case 43: break;
        case 10: 
          { lexeme = yytext(); return COMA;
          }
        case 44: break;
        case 35: 
          { return SWITCH;
          }
        case 45: break;
        case 18: 
          { return MULTIPLICACION;
          }
        case 46: break;
        case 34: 
          { return FALSE;
          }
        case 47: break;
        case 5: 
          { lexeme = yytext(); return TERMCOR;
          }
        case 48: break;
        case 3: 
          { lexeme = yytext(); return NUMERO;
          }
        case 49: break;
        case 28: 
          { return CHAR;
          }
        case 50: break;
        case 17: 
          { return RESTA;
          }
        case 51: break;
        case 23: 
          { return MENOROIGUAL;
          }
        case 52: break;
        case 25: 
          { return INT;
          }
        case 53: break;
        case 19: 
          { return SUMA;
          }
        case 54: break;
        case 8: 
          { lexeme = yytext(); return CERRPAR;
          }
        case 55: break;
        case 13: 
          { return DIVISION;
          }
        case 56: break;
        case 9: 
          { lexeme = yytext(); return DOSPUNT;
          }
        case 57: break;
        case 31: 
          { return CLASS;
          }
        case 58: break;
        case 29: 
          { return ELSE;
          }
        case 59: break;
        case 22: 
          { return IGUAL;
          }
        case 60: break;
        case 32: 
          { return FLOAT;
          }
        case 61: break;
        case 27: 
          { return CASE;
          }
        case 62: break;
        case 33: 
          { return WHILE;
          }
        case 63: break;
        case 14: 
          { return MAYORQUE;
          }
        case 64: break;
        case 7: 
          { lexeme = yytext(); return APERPAR;
          }
        case 65: break;
        case 1: 
          { return ERROR;
          }
        case 66: break;
        case 30: 
          { return TRUE;
          }
        case 67: break;
        case 26: 
          { return FOR;
          }
        case 68: break;
        case 37: 
          { return DEFAULT;
          }
        case 69: break;
        case 15: 
          { return ASIGNA;
          }
        case 70: break;
        case 12: 
          { /*Ignore*/
          }
        case 71: break;
        case 6: 
          { return PUNTOYCOMA;
          }
        case 72: break;
        case 4: 
          { lexeme = yytext(); return INITCOR;
          }
        case 73: break;
        case 24: 
          { return DIFERENTEQUE;
          }
        case 74: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
